'use client'

import Link from 'next/link'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, FileSearch, Landmark, Menu, Search, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/android-chrome-512x512-YhKIDRg6yr67e0OPyc7HYfbCu4I0VI.png'
const nav = [['Home', '/'], ['Elections', '/elections'], ['Results', '/results'], ['How It Works', '/how-it-works'], ['About', '/about']]
type Status = 'active' | 'scheduled' | 'review' | 'completed'
type Election = { id: string; name: string; slug: string; description: string; status: Status; startsAt?: string; endsAt?: string; eligibility: string }

const elections: Election[] = []
const statusInfo: Record<Status, { label: string; description: string; className: string }> = {
  active: { label: 'Voting Open', description: 'Voting is currently open.', className: 'status-active' },
  scheduled: { label: 'Upcoming', description: 'Voting has not started.', className: 'status-scheduled' },
  review: { label: 'Results Under Review', description: 'Voting has ended and results are being reviewed.', className: 'status-review' },
  completed: { label: 'Results Published', description: 'Results have been officially published.', className: 'status-completed' },
}

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="site-container header-inner"><Link href="/" className="wordmark"><img src={logo} alt="" /><span>FUTO <b>Central</b><em>Elections</em></span></Link><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={label} href={href} className={label === 'Elections' ? 'active' : ''}>{label}</Link>)}</nav><div className="header-actions"><Link href="/elections" className="header-cta">View Elections <ArrowRight size={15} /></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></div>{open && <div className="mobile-menu"><nav aria-label="Mobile navigation">{nav.map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)}>{label}<ArrowRight size={15} /></Link>)}<Link href="/elections" className="mobile-cta" onClick={() => setOpen(false)}>View Elections<ArrowRight size={15} /></Link></nav></div>}</header>
}

function PageIntro() { return <section className="directory-hero"><div className="site-container directory-hero-inner"><div><span className="eyebrow">FUTO CENTRAL ELECTIONS</span><h1>Elections</h1><p>Explore current, upcoming, and completed student elections, and find out when you can participate.</p></div><div className="directory-mark" aria-hidden="true"><Landmark size={30} /><span>PUBLIC<br />DIRECTORY</span></div></div></section> }

function FilterBar({ active, setActive, search, setSearch }: { active: string; setActive: (value: string) => void; search: string; setSearch: (value: string) => void }) { const filters = [['all', 'All'], ['active', 'Active'], ['scheduled', 'Upcoming'], ['review', 'In Review'], ['completed', 'Completed']]; return <div className="directory-tools"><div className="filter-tabs" role="tablist" aria-label="Filter elections by status">{filters.map(([value, label]) => <button key={value} role="tab" aria-selected={active === value} className={active === value ? 'selected' : ''} onClick={() => setActive(value)}>{label}</button>)}</div><label className="election-search"><Search size={16} /><span className="sr-only">Search elections</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search elections" /></label></div> }

function ElectionCard({ election }: { election: Election }) { const info = statusInfo[election.status]; return <article className="election-card"><div className="election-card-top"><span className={`status-badge ${info.className}`}><i />{info.label}</span><span className="card-type">Student election</span></div><h3>{election.name}</h3><p className="election-description">{election.description}</p><div className="election-details"><div><CalendarDays size={16} /><span><b>{election.status === 'scheduled' ? 'Voting starts' : 'Voting period'}</b>{election.startsAt ?? 'Date to be announced'}{election.endsAt && <> <br />Closes {election.endsAt}</>}</span></div><div><ShieldCheck size={16} /><span><b>Eligible voters</b>{election.eligibility}</span></div></div><div className="election-card-footer">{election.status === 'active' && <Link href={`/elections/${election.slug}/vote`} className="button button-primary">Vote Now <ArrowRight size={16} /></Link>}{election.status === 'completed' && <Link href={`/elections/${election.slug}/results`} className="button button-primary">View Results <ArrowRight size={16} /></Link>}{election.status === 'scheduled' && <span className="card-note"><Clock3 size={15} /> Voting has not started</span>}{election.status === 'review' && <span className="card-note"><FileSearch size={15} /> Results are under review</span>}</div></article> }

function EmptyState({ filter }: { filter: string }) { const copy = filter === 'active' ? ['No active elections', 'There are no elections currently open for voting.'] : filter === 'scheduled' ? ['No upcoming elections', 'There are no scheduled elections at this time.'] : filter === 'completed' ? ['No election results published', 'No election results have been published yet.'] : ['No elections available', 'There are currently no elections to display. Check back when a new election is scheduled.']; return <div className="directory-empty"><div className="empty-icon"><Landmark size={24} /></div><h2>{copy[0]}</h2><p>{copy[1]}</p></div> }

function StatusLegend() { return <div className="directory-legend"><span className="eyebrow">Status guide</span>{(['active', 'scheduled', 'review', 'completed'] as Status[]).map((status) => <div key={status}><i className={`status-dot ${statusInfo[status].className}`} /><span><b>{statusInfo[status].label}</b>{statusInfo[status].description}</span></div>)}</div> }

function Footer() { return <footer className="site-footer"><div className="site-container footer-grid"><div className="footer-brand"><Link href="/" className="wordmark light"><img src={logo} alt="" /><span>FUTO <b>Central</b><em>Elections</em></span></Link><p>Organized, transparent, and accessible student elections for the FUTO community.</p></div><div className="footer-links"><div><h3>Platform</h3><Link href="/">Home</Link><Link href="/elections">Elections</Link><Link href="/results">Results</Link><Link href="/how-it-works">How It Works</Link></div><div><h3>Information</h3><Link href="/about">About</Link><Link href="/election-guidelines">Election Guidelines</Link><Link href="/data-policy">Data Sources &amp; Retention</Link><Link href="/contact">Contact</Link></div><div><h3>Administration</h3><Link href="/admin/login">Admin Login</Link></div></div></div><div className="site-container footer-bottom"><span>© 2026 FUTO Central Elections. All rights reserved.</span><span>Independent. Useful. Connected.</span></div></footer> }

export default function ElectionsPage() { const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const visible = elections.filter((election) => (filter === 'all' || election.status === filter) && election.name.toLowerCase().includes(search.toLowerCase())); return <div className="elections-site"><Header /><main><PageIntro /><section className="directory-section"><div className="site-container"><FilterBar active={filter} setActive={setFilter} search={search} setSearch={setSearch} />{visible.length ? <div className="election-grid">{visible.map((election) => <ElectionCard key={election.id} election={election} />)}</div> : <EmptyState filter={filter} />}<StatusLegend /></div></section><section className="directory-note"><div className="site-container directory-note-inner"><Check size={20} /><p>Election information will appear here when elections are scheduled or opened for participation. Each election will clearly show its status, dates, eligibility, and next available action.</p></div></section></main><Footer /></div> }

export function ElectionCardSkeleton() { return <div className="election-card skeleton-card" aria-label="Loading election"><span /><span /><span /><span /></div> }
export function ElectionsErrorState({ onRetry }: { onRetry?: () => void }) { return <div className="directory-empty"><div className="empty-icon"><FileSearch size={24} /></div><h2>We couldn&apos;t load the elections right now.</h2><p>Please try again in a moment.</p>{onRetry && <button className="button button-primary" onClick={onRetry}>Try Again</button>}</div> }

