'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, ChevronDown, CircleCheck, FileCheck2, Landmark, Menu, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/android-chrome-512x512-YhKIDRg6yr67e0OPyc7HYfbCu4I0VI.png'
const nav = [['Home','/'],['Elections','/elections'],['Results','/results'],['How It Works','/how-it-works'],['About','/about']]

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="site-container header-inner"><Link href="/" className="wordmark"><img src={logo} alt="" /><span>FUTO <b>Central</b><em>Elections</em></span></Link><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={label} href={href} className={label === 'Home' ? 'active' : ''}>{label}</Link>)}</nav><div className="header-actions"><Link href="/elections" className="header-cta">View Elections <ArrowRight size={15} /></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></div>{open && <div className="mobile-menu"><nav aria-label="Mobile navigation">{nav.map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)}>{label}<ArrowRight size={15} /></Link>)}<Link href="/elections" className="mobile-cta" onClick={() => setOpen(false)}>View Elections<ArrowRight size={15} /></Link></nav></div>}</header>
}

function Hero() { return <section className="hero"><div className="site-container hero-grid"><div className="hero-copy"><span className="eyebrow">FUTO CENTRAL</span><h1>FUTO Central <span>Elections</span></h1><p className="hero-kicker">Your voice. Your vote. Your future.</p><p className="hero-text">A digital platform designed to make FUTO student elections organized, accessible, transparent, and easy to participate in.</p><div className="hero-actions"><Link href="/elections" className="button button-primary">View Elections <ArrowRight size={17} /></Link><Link href="/how-it-works" className="button button-quiet">How It Works <ArrowRight size={17} /></Link></div></div><div className="hero-art" aria-label="Illustration of a digital ballot interface"><div className="art-top"><span>FUTO CENTRAL</span><span className="art-status"><i /> PLATFORM READY</span></div><div className="art-panel"><div className="art-check"><Check size={31} /></div><div><span className="art-label">STUDENT ELECTIONS</span><strong>Your voice<br />belongs here.</strong></div></div><div className="art-list"><div><span className="mini-dot green" /> Eligible participation <Check size={15} /></div><div><span className="mini-dot gold" /> Clear election status <Check size={15} /></div><div><span className="mini-dot dark" /> Reviewed results <Check size={15} /></div></div><div className="art-footer"><span>FUTO community</span><span>01 / 03</span></div></div></div></section> }

const steps = [{ title: 'Find Your Election', text: 'Browse available elections and identify the ones currently open for voting.', icon: Landmark }, { title: 'Verify Your Eligibility', text: 'Provide the required information so the system can determine your eligibility.', icon: ShieldCheck }, { title: 'Access Your Ballot', text: 'Eligible students receive access to the ballot associated with the election.', icon: FileCheck2 }, { title: 'Make Your Choices', text: 'Review the available candidates and select your preferred choices.', icon: Users }, { title: 'Cast Your Vote', text: 'Review your selections carefully, then submit your vote.', icon: CircleCheck }]
function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function Intro() { return <section className="section intro-section"><div className="site-container intro-grid"><SectionIntro eyebrow="A better way to participate" title="Built for FUTO Student Elections" text="FUTO Central Elections provides a structured digital environment where eligible students can participate according to the rules established for each election." /><div className="intro-note"><Sparkles size={20} /><p>Different elections may serve different communities — from university-wide and school-level elections to departmental and level-specific participation.</p></div></div></section> }
function HowItWorks() { return <section className="section muted-section"><div className="site-container"><SectionIntro eyebrow="The process" title="How Voting Works" text="A clear path from finding an election to making your voice count." /><div className="steps-grid">{steps.map((step, i) => { const Icon = step.icon; return <article className="step-card" key={step.title}><div className="step-number">0{i + 1}</div><Icon className="step-icon" size={24} /><h3>{step.title}</h3><p>{step.text}</p></article> })}</div></div></section> }
const statuses = [['Scheduled','Voting has not started.','status-scheduled'],['Active','Voting is currently open.','status-active'],['In Review','Voting has ended and results are being reviewed.','status-review'],['Completed','Results have been officially published.','status-completed']]
function ElectionsPreview() { return <section className="section"><div className="site-container"><div className="split-heading"><SectionIntro eyebrow="Participation" title="Elections" text="Browse current, upcoming, and completed elections." /><Link href="/elections" className="text-link">View all elections <ArrowRight size={16} /></Link></div><div className="empty-panel"><div className="empty-icon"><Landmark size={25} /></div><h3>Elections will appear here</h3><p>They will be listed when scheduled or opened for participation.</p><Link href="/elections" className="button button-primary">View All Elections <ArrowRight size={16} /></Link></div><div className="status-grid">{statuses.map(([title, text, cls]) => <div className="status-item" key={title}><span className={`status-dot ${cls}`} /><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></div></section> }
function Eligibility() { return <section className="section deep-section"><div className="site-container two-col"><div><span className="eyebrow eyebrow-light">Participation, by design</span><h2>Eligibility Matters</h2></div><div><p className="large-light">Every election can be configured for the community it serves. Eligibility may be based on school, department, academic level, or other approved election-specific requirements.</p><p className="muted-light">Before ballot access, the platform checks whether a student is eligible for that particular election.</p></div></div></section> }
function Verification() { return <section className="section"><div className="site-container verification-grid"><div className="verification-card"><div className="verification-orbit"><ShieldCheck size={35} /></div><span className="eyebrow">Trust by design</span><h2>Designed to Protect the Integrity of Every Election</h2><p>The platform uses student information to verify that a person attempting to vote corresponds to an eligible student record.</p><div className="verification-tags"><span>JAMB Registration Number</span><span>State of Origin</span><span>Election rules</span></div></div><div className="verification-copy"><p>Verification is intended to ensure that only eligible students can participate in the appropriate election. The information requested may vary depending on the requirements of that election.</p><Link href="/data-policy" className="text-link">Learn About Our Data Practices <ArrowRight size={16} /></Link></div></div></section> }
function Transparency() { return <section className="section muted-section"><div className="site-container"><SectionIntro eyebrow="A visible lifecycle" title="Transparent From Voting to Results" text="Voting ending and results being published are separate stages — so everyone knows where an election stands." /><div className="lifecycle">{['Election Scheduled','Voting Opens','Students Vote','Voting Closes','Results Under Review','Results Published'].map((item, i) => <div className="lifecycle-item" key={item}><span>{String(i + 1).padStart(2, '0')}</span><strong>{item}</strong>{i < 5 && <ArrowRight size={17} />}</div>)}</div></div></section> }
function Results() { return <section className="section results-section"><div className="site-container results-panel"><div><span className="eyebrow">Public record</span><h2>Election Results</h2><p>Explore results from elections whose outcomes have been officially published.</p></div><div className="result-empty"><span>No election results have been published yet.</span><Link href="/results" className="button button-primary">View Results <ArrowRight size={16} /></Link></div></div></section> }
function DataTransparency() { return <section className="section"><div className="site-container data-grid"><SectionIntro eyebrow="Transparency matters" title="Your Data, Used With Purpose" text="Student information used for election eligibility is intended to come from clearly identified sources and support legitimate election administration purposes." /><div className="principles"><div className="principle-list">{['Purpose limitation','Data minimization','Responsible retention','Appropriate security','Limited access'].map(x => <div key={x}><Check size={16} />{x}</div>)}</div><Link href="/data-policy" className="text-link">Read Our Data Policy <ArrowRight size={16} /></Link></div></div></section> }
function Guidelines() { const cards = [['How voting works','Understand each stage of participation.','/how-it-works'],['Election guidelines','Review the principles for taking part.','/election-guidelines'],['Eligibility information','Learn why requirements can differ.','/about'],['Data policy','See how information is used with purpose.','/data-policy']]; return <section className="section muted-section"><div className="site-container"><SectionIntro eyebrow="Be informed" title="Know Before You Vote" text="Good participation starts with understanding the process." /><div className="guidelines-grid">{cards.map(([title, text, href], i) => <Link href={href} className="guide-card" key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p><ArrowRight size={17} /></Link>)}</div></div></section> }
const faqs = [['Who can vote?','Eligibility depends on the rules configured for each election.'],['How do I know if an election is currently open?','The Elections page displays the current status of every election.'],['Why do I need to verify my student information?','Verification helps determine whether you are eligible to participate in a particular election.'],['Can I vote more than once?','The election system is designed to prevent a student from casting more than one ballot in the same election.'],['When can I see election results?','Results become publicly available after voting has ended, the results have been reviewed, and an administrator has officially published them.'],['Where does the student information used for verification come from?','Students can learn more on the Data Policy page.']]
function FAQ() { const [active, setActive] = useState<number | null>(null); return <section className="section faq-section"><div className="site-container faq-grid"><SectionIntro eyebrow="Questions, answered" title="Frequently Asked Questions" text="A quick guide to how the platform is intended to work." /><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${active === i ? 'open' : ''}`} key={q}><button onClick={() => setActive(active === i ? null : i)} aria-expanded={active === i}><span>{q}</span><ChevronDown size={18} /></button>{active === i && <p>{a}</p>}</div>)}</div></div></section> }
function FinalCTA() { return <section className="final-cta"><div className="site-container final-cta-inner"><div><span className="eyebrow eyebrow-light">Take part</span><h2>Make Your Voice Count</h2><p>Check the latest elections and find out where you can participate.</p></div><Link href="/elections" className="button button-gold">View Elections <ArrowRight size={17} /></Link></div></section> }
function Footer() { return <footer className="site-footer"><div className="site-container footer-grid"><div className="footer-brand"><Link href="/" className="wordmark light"><img src={logo} alt="" /><span>FUTO <b>Central</b><em>Elections</em></span></Link><p>Organized, transparent, and accessible student elections for the FUTO community.</p></div><div className="footer-links"><div><h3>Platform</h3><Link href="/">Home</Link><Link href="/elections">Elections</Link><Link href="/results">Results</Link><Link href="/how-it-works">How It Works</Link></div><div><h3>Information</h3><Link href="/about">About</Link><Link href="/election-guidelines">Election Guidelines</Link><Link href="/data-policy">Data Sources &amp; Retention</Link><Link href="/contact">Contact</Link></div><div><h3>Administration</h3><Link href="/admin/login">Admin Login</Link></div></div></div><div className="site-container footer-bottom"><span>© 2026 FUTO Central Elections. All rights reserved.</span><span>Independent. Useful. Connected.</span></div></footer> }

export default function ElectionsHomepage() { return <div className="elections-site"><Header /><main><Hero /><Intro /><HowItWorks /><ElectionsPreview /><Eligibility /><Verification /><Transparency /><Results /><DataTransparency /><Guidelines /><FAQ /><FinalCTA /></main><Footer /></div> }
